#plugins:
#  - jekyll-relative-links
#relative_links:
#  enabled: true
#  collections: true
#include:
#  - proposal.md

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true

remote_theme: pages-themes/cayman@v0.2.0

include:
  - index.md
  - proposal.md
  - midterm.md