#plugins:
#  - jekyll-relative-links
#relative_links:
#  enabled: true
#  collections: true
#include:
#  - proposal.md

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - proposal.md
  - midterm.md